### ISSUE TITLE
How to find out what MCU to delete/copy/add

### ISSUE THREAD

**Issue by phirestalker** [dmahurin/jpegrepair#9]
I have some damaged JPG files. Probably from bitrot. I think your tool would be able to fix them easily, but how do I find the numbers to put into the command? I can see in the image viewer where the messup is, but I do not know what number MCU it is. Is there some kind of a scan command? Do you use other software to analyze the JPEGs before repair?

Thanks

**Comment by DRCRecoveryData** [comment]
> I have some damaged JPG files. Probably from bitrot. I think your tool would be able to fix them easily, but how do I find the numbers to put into the command? I can see in the image viewer where the messup is, but I do not know what number MCU it is. Is there some kind of a scan command? Do you use other software to analyze the JPEGs before repair?
> 
> 
> 
> Thanks

Can you upload jpg file zipped to here?

**Comment by phirestalker** [comment]
Sorry, I found a program that lets me do it graphically. Thanks.

**Comment by dmahurin** [comment]
@phirestalker , glad you found a solution.

If you wish to try again with this tool,

You first need to find the MCU block dimensions. With no arguments, you will see how to do this.

Show block dimensions using 'dest' with no other arguments

./jpegrepair before.jpg after.jpg dest

which will print something like this:

mcu blocks HxW = 260x125

Since this is not graphical, you would need to guess to find the location of interest,  but the block dimensions are small, so it should not take many guesses.

Try to insert or delete a block to see the location change.

./jpegrepair before.jpg after.jpg dest 100 0 insert 5

You could see the change. Once you find the location, then you can make the desired modifications.
